name: Hadoop3
on: 
  push:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: branch-3.3.1
      - name: build hadoop
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run:
          sudo apt-get -y install openjdk-8-jdk
          sudo apt-get -y install maven
