name: Hadoop3
on: 
  push:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialization environment
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: |
          sudo lsb_release -a
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get -y install maven
          sudo mvn package -Pdist,native -DskipTests -Dtar
          
          
          
