name: Hadoop3
on: 
  push:
    branches: [ trunk ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: branch-3.3.1
      - name: build hadoop
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run:
          sudo apt-get -y install openjdk-8-jdk
          sudo apt-get -y install maven
          
          sudo curl https://github.com/protocolbuffers/protobuf/releases/download/v3.20.1/protobuf-all-3.20.1.tar.gz
          sudo mkdir protobuf-3.20-src
          sudo mv protobuf-all-3.20.1.tar.gz protobuf-3.20-src
          cd protobuf-3.20-src
          sudo tar xzf protobuf-all-3.20.1.tar.gz
          sudo ./configure
          sudo make install
          cd /home/runner/work/hadoop331/hadoop331/
          mvn package -DskipTests -Pdist,native -Dtar -Dbundle.snappy -Drequire.snappy -Dbundle.pmdk -Drequire.pmdk -Dbundle.lz4 -Drequire.lz4
