name: Hadoop3
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Initialization environment
        env:
          JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
        run: |
          sudo lsb_release -a
          sudo apt-get install -y openjdk-8-jdk
          sudo export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          sudo apt-get -y install maven
          sudo mvn package -Pdist,native -DskipTests -Dtar
          
          
          
